<script src="{{ asset("admin/assets/vendor/libs/jquery/jquery.js") }}"></script>
<script src="{{ asset("admin/assets/vendor/libs/popper/popper.js") }}"></script>
<script src="{{ asset("admin/assets/vendor/js/bootstrap.js") }}"></script>
<script src="{{ asset("admin/assets/vendor/libs/node-waves/node-waves.js") }}"></script>
<script src="{{ asset(" admin/assets/vendor/libs/@algolia/autocomplete-js.js") }}"></script>
<script src="{{ asset("admin/assets/vendor/libs/pickr/pickr.js") }}"></script>
<script src="{{ asset("admin/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js") }}"></script>
<script src="{{ asset("admin/assets/vendor/libs/hammer/hammer.js") }}"></script>
<script src="{{ asset("admin/assets/vendor/libs/i18n/i18n.js") }}"></script>
<script src="{{ asset("admin/assets/vendor/js/menu.js") }}"></script>
<script src="{{ asset("admin/assets/vendor/libs/cleave-zen/cleave-zen.js") }}"></script>
<script src="{{ asset("admin/assets/vendor/libs/jquery-repeater/jquery-repeater.js") }}"></script>
<script src="{{ asset("admin/assets/js/main.js") }}"></script>
<script src="{{ asset("admin/assets/js/forms-extras.js") }}"></script>